-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR , MONTH(SALES_DATE)as MONTH , GENDER , COUNT(DISTINCT I.USER_ID) as USERS
FROM USER_INFO as I JOIN
    ONLINE_SALE as O 
    ON I.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE) , MONTH(SALES_DATE) , GENDER
ORDER BY YEAR(SALES_DATE) , MONTH(SALES_DATE) , GENDER ;