WITH TMP AS 
 (SELECT A.CAR_ID,A.CAR_TYPE,A.DAILY_FEE,C.DURATION_TYPE,C.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR A JOIN 
         CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
      ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_TYPE IN ('세단','SUV') AND C.DURATION_TYPE='30일 이상')

SELECT DISTINCT A.CAR_ID,
       A.CAR_TYPE, 
       ROUND((30 * A.DAILY_FEE * (1 - A.DISCOUNT_RATE/100 )),0) as FEE 
FROM TMP A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
WHERE  A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
        TO_CHAR(START_DATE,'YYYY-MM-DD') BETWEEN '2022-11-01' AND '2022-11-30'
        OR TO_CHAR(END_DATE,'YYYY-MM-DD') BETWEEN '2022-11-01' AND '2022-11-30'
        OR (TO_CHAR(START_DATE,'YYYY-MM-DD') < '2022-11-01' AND
            TO_CHAR(END_DATE,'YYYY-MM-DD')>'2022-11-30'))
        AND 30 * A.DAILY_FEE * (1 - A.DISCOUNT_RATE/100 ) >= 500000
        AND 30 * A.DAILY_FEE * (1 - A.DISCOUNT_RATE/100 ) < 2000000 
ORDER BY 3 DESC , 2 , 1 DESC ;