-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) , MONTH(SALES_DATE) , COUNT(DISTINCT(O.USER_ID)) as PUCHASED_USERS , ROUND(COUNT(DISTINCT(O.USER_ID))/ (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) as PUCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O
    ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY 1,2
ORDER BY 1 ,2;