WITH RECURSIVE HOURTABLE AS 
    (SELECT 0 AS HOUR 
     UNION ALL 
     SELECT HOUR+1 FROM HOURTABLE
     WHERE HOUR<23
    )

SELECT H.HOUR, COUNT(O.ANIMAL_ID) as COUNT
FROM HOURTABLE H LEFT OUTER JOIN ANIMAL_OUTS O
    ON H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY 1