-- 코드를 입력하세요
SELECT U.USER_ID as USER_ID ,U.NICKNAME as NICKNAME
, CONCAT(U.CITY," ",U.STREET_ADDRESS1," ",U.STREET_ADDRESS2) as 전체주소
, CONCAT(SUBSTR(U.TLNO,1,3),"-",SUBSTR(U.TLNO,4,4),"-",SUBSTR(U.TLNO,8,4)) as 전화번호
FROM USED_GOODS_BOARD as B 
    JOIN USED_GOODS_USER as U
    ON B.WRITER_ID = U.USER_ID 
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY 1 DESC ;