SELECT A.REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE),2) as SCORE
FROM REST_INFO as A JOIN REST_REVIEW as B USING(REST_ID) 
WHERE ADDRESS LIKE "서울%"
GROUP BY A.REST_ID
ORDER BY 6 DESC ,FAVORITES DESC;