-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") as DATE_FORMAT
FROM MEMBER_PROFILE M JOIN REST_REVIEW  R
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = ( SELECT MEMBER_ID
                      FROM REST_REVIEW
                      GROUP BY MEMBER_ID
                      ORDER BY COUNT(R.MEMBER_ID) desc
                      LIMIT 1)
ORDER BY REVIEW_DATE , REVIEW_TEXT ;