WITH WHOLECOUNT AS
(
SELECT COUNT(DISTINCT USER_ID) AS COUNT
FROM USER_INFO
WHERE YEAR(JOINED)=2021
)

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
   COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS,
   ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT FROM WHOLECOUNT),1) AS PUCHASED_RATIO
FROM USER_INFO A JOIN ONLINE_SALE B USING(USER_ID)
WHERE YEAR(JOINED)=2021
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)
ORDER BY 1,2