-- 코드를 입력하세요
SELECT CATEGORY , SUM(SALES) as TOTAL_SALES
FROM BOOK as B JOIN BOOK_SALES as BS on B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY;