-- 코드를 입력하세요
SELECT B.AUTHOR_ID , AUTHOR_NAME, CATEGORY, SUM(B.PRICE * S.SALES) as TOTAL_PRICE
FROM BOOK as B 
 LEFT JOIN AUTHOR as A
 ON B.AUTHOR_ID = A.AUTHOR_ID
 LEFT JOIN BOOK_SALES as S
 ON B.BOOK_ID = S.BOOK_ID AND DATE_FORMAT(SALES_DATE,"%Y-%m")="2022-01" 
GROUP BY B.AUTHOR_ID , CATEGORY
ORDER BY B.AUTHOR_ID , CATEGORY DESC;