SELECT PRODUCT_ID,PRODUCT_NAME,SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B USING(PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY PRODUCT_NAME
ORDER BY 3 DESC, 1 ;

