-- 코드를 입력하세요
SELECT A.PRODUCT_CODE , SUM(PRICE*SALES_AMOUNT) as SALES
FROM PRODUCT as A
INNER JOIN OFFLINE_SALE as B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC , PRODUCT_CODE ;
