WITH FH AS
(
SELECT SHIPMENT_ID,FLAVOR,SUM(TOTAL_ORDER) AS SUM
FROM FIRST_HALF
GROUP BY FLAVOR
),
J AS (
SELECT SHIPMENT_ID,FLAVOR,SUM(TOTAL_ORDER) AS SUM
FROM JULY
GROUP BY FLAVOR
)

SELECT A.FLAVOR
FROM FH A JOIN J B USING(SHIPMENT_ID)
ORDER BY A.SUM+B.SUM DESC
LIMIT 3;
