WITH FIND as (
    SELECT *
    FROM PATIENT A JOIN APPOINTMENT B USING(PT_NO)
    WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d')='2022-04-13' AND MCDP_CD = 'CS' AND APNT_CNCL_YN='N'
)

SELECT APNT_NO,PT_NAME,PT_NO,A.MCDP_CD,DR_NAME,
      APNT_YMD
FROM FIND A JOIN DOCTOR B ON DR_ID=MDDR_ID
ORDER BY 6;

