-- 코드를 입력하세요
SELECT HISTORY_ID ,CAR_ID,date_format(START_DATE,'%Y-%m-%d'),date_format(END_DATE,'%Y-%m-%d'), 
IF( (DATEDIFF(END_DATE,START_DATE)>=29),"장기 대여","단기 대여") as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)='2022' AND MONTH(START_DATE)='09'
ORDER BY HISTORY_ID DESC;