SELECT B.HISTORY_ID, FLOOR( (DATEDIFF(END_DATE,START_DATE)+1) * DAILY_FEE * ( 1 -(IFNULL(C.DISCOUNT_RATE,0)/100)) )
FROM CAR_RENTAL_COMPANY_CAR as A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE 
      AND C.DURATION_TYPE = ( 
         CASE 
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN '7일 이상'
        END
          )
WHERE A.CAR_TYPE='트럭' 
GROUP BY B.HISTORY_ID
ORDER BY 2 DESC , 1 DESC ;