-- 코드를 입력하세요
SELECT P.PRODUCT_ID,PRODUCT_NAME , PRICE*SUM(AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as P JOIN FOOD_ORDER as O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC , 1 ;